export const photos = [
  {
    id: 0,
    name: "jellyfish in the sky",
    type: "photo",
    source: "assets/images/photography/p1.jpeg",
    horizontal: true,
  },
  {
    id: 1,
    name: "night is coming",
    type: "photo",
    source: "assets/images/photography/p2.jpeg",
    horizontal: true,
  },
  {
    id: 2,
    name: "evening light",
    type: "photo",
    source: "assets/images/photography/p3.jpeg",
    horizontal: true,
  },
  {
    id: 3,
    name: "peaceful sky",
    type: "photo",
    source: "assets/images/photography/p4.jpeg",
    horizontal: true,
  },
  {
    id: 4,
    name: "sweet dream",
    type: "photo",
    source: "assets/images/photography/p5.jpg",
    horizontal: true,
  },
  {
    id: 5,
    name: "stuck in a rut",
    type: "photo",
    source: "assets/images/photography/p6.jpg",
    horizontal: true,
  },
  {
    id: 6,
    name: "light of hope",
    type: "photo",
    source: "assets/images/photography/p7.jpg",
    horizontal: true,
  },
  {
    id: 7,
    name: "aesthetic of nature",
    type: "photo",
    source: "assets/images/photography/p8.jpg",
    horizontal: true,
  },

  {
    id: 8,
    name: "so cool building",
    type: "photo",
    source: "assets/images/photography/p10.jpg",
    horizontal: true,
  },
  {
    id: 9,
    name: "where am i going?",
    type: "photo",
    source: "assets/images/photography/p11.jpg",
    horizontal: true,
  },
  {
    id: 10,
    name: "life journey",
    type: "photo",
    source: "assets/images/photography/p12.jpg",
    horizontal: true,
  },
  {
    id: 11,
    name: "rest in peace",
    type: "photo",
    source: "assets/images/photography/p13.jpg",
    horizontal: true,
  },
  {
    id: 12,
    name: "it looks happy!",
    type: "photo",
    source: "assets/images/photography/p14.jpg",
    horizontal: true,
  },
  {
    id: 13,
    name: "my cutest boy",
    type: "photo",
    source: "assets/images/photography/p15.jpg",
    horizontal: true,
  },
  {
    id: 14,
    name: "look at that cheek! ",
    type: "photo",
    source: "assets/images/photography/p16.jpg",
    horizontal: true,
  },
  {
    id: 15,
    name: "you'll smile",
    type: "photo",
    source: "assets/images/photography/p17.jpg",
    horizontal: true,
  },
];
